<ips:template parameters="$members,$guests,$anonymous,$bots,$memberCount,$orientation" />
<h3 class="ipsType_reset ipsWidget_title">
	{lang="block_whosOnline"}
	{{if $orientation == 'horizontal'}}
	{{$guests = $guests + $bots['count'];}}
		&nbsp;&nbsp;<span class="ipsType_light ipsType_unbold ipsType_medium">{lang="block_whos_online_info_members" pluralize="$memberCount"}, {lang="block_whos_online_info_anonymous" pluralize="$anonymous"}, {lang="block_whos_online_info_guests" pluralize="$guests"}</span>
	{{endif}}
	<span class="ipsType_medium ipsType_light ipsType_unbold ipsType_blendLinks">
        <a href="{url="app=core&module=online&controller=online" seoTemplate="online"}">{lang="see_full_list"}</a>
    </span>
</h3>