<ips:template parameters="$bots" />
{{if $bots['count'] > 0}}
	{{$prefixsuffix = explode( ',', \IPS\Settings::i()->botsInOnlineList_prefixsuffix );}}
	<h6 class='ipsType_reset ipsType_medium'>{lang="botsInOnlineList_title"}:</h6>
	<ul class='ipsList_inline ipsList_csv ipsList_noSpacing'>
		{{foreach $bots['bots'] as $bot}}
			<li>{$prefixsuffix[0]|raw}{$bot}{$prefixsuffix[1]|raw}</li>
		{{endforeach}}
	</ul>
{{endif}}